import { run } from "./harness";
import "./cards/regirock-ex";
import "./cards/dark-registeel";
import "./cards/light-regice";
import "./cards/spelling";
import "./cards/quagsire";
import "./cards/slugma";
import "./cards/abra";
import "./cards/pikachu";
import "./cards/magneton";
import "./cards/lairon";
import "./cards/miltank";
import "./cards/gligar";
import "./cards/magcargo";
import "./cards/poke-bodies";
import "./cards/dragon";
import "./cards/nidoran";
import "./cards/gengar-line";
import "./cards/fire";
import "./cards/water";
import "./cards/sky";
import "./cards/electric";
import "./cards/ground";
import "./cards/legend";
import "./cards/dark";
import "./cards/styns-hitmonlee";
import "./cards/crystal";
import "./cards/aggron";
import "./cards/alakazam";
import "./cards/buried-relic-mew";
import "./cards/houndour";
import "./cards/houndoom";
import "./cards/linoone";
import "./cards/machamp";
import "./cards/magnezone";
import "./cards/nidoqueen";
import "./cards/nidoran-f";
import "./cards/nidorina";
import "./cards/noctowl";
import "./cards/porygon-z";
import "./cards/porygon2";
import "./cards/raichu";
import "./cards/sableye";
import "./cards/sealeo";
import "./cards/snorlax";
import "./cards/spheal";
import "./cards/walrein";
import "./cards/energy-recycle-system";
import "./cards/life-herb";
import "./cards/mt-moon";
import "./cards/space-center";
import "./cards/meteor-falls";
import "./deck-validation";

declare const process: { argv: string[]; exitCode?: number };

if (run(process.argv[2]) > 0) process.exitCode = 1;
